language: java
jdk: openjdk8


before_install:
  - sudo sh -c 'echo "deb https://packages.atlassian.com/debian/atlassian-sdk-deb/ stable contrib" >>/etc/apt/sources.list'
  - wget https://packages.atlassian.com/api/gpg/key/public
  - sudo apt-key add public
  - sudo apt-get update
  - sudo apt-get install atlassian-plugin-sdk
  - atlas-version
install: skip

stages:
  - test
  - name: build and release
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch IN (master, cp-29-travis-release-to-github)
jobs:
  include:
    - stage: test
      script: atlas-unit-test
    - stage: build and release
      script:
        - atlas-package
        - ls -l ./target
      deploy:
        provider: releases
        api_key:
          secure: P1zTdiHmM7CJS5HBgB6VDlvo9iALxF/oDTp4y9gu2dWJK7j5dqWuJbfnqYllf4W3uJu8kw20qXVJeaGIt0+11XEK6loQQX20MvMTvHET5CRyg5ZiMDyvUSF+EGPHj4k/Vj8oBRQxuNe5KkT/P0dKuvETQA9ZCMMLMLyxPp49fNK8X51txcArowjFfASo1QbSMN0VGOwiSEHH8GHhz0752p76GdFdpvfoAuGyXcfcFIrQn0/+Uu5vw0qSob6bk72Xy7rWxlvi1VhuvjL8rMm+R7aGZ9SJ+BBQS1V7cymYWDqSsBukxV6uYnQZ9LfRz3r0uht7W9GQ8mPyt3CWxZSA3306lRl1Y52gWa244T81ETIyvOkDMpxGD3memRqnSs7/b1gcy7VRmvg7IQCzV53cKlWaq6qWHZ/N7KSQ65BqlOJVm4sfGSNvQRt2vB5/MkKXgapS+OeyJfn0pZWOU9gkR+7iolTKANCSRq/Dqt/0PBYd2yRZxmqXWb5i6Zh/uGOcFM0+TS36Qn+EvNsMxl+n0s+IbPAGVjvTg3vBnutlYSo4G4i+ue3M4DCQv2oUNDr+js3N33Cm2gemz+2GSLTghq6QEYDnfKfWM3LdvV7K9o0T7FWWv4kMuny1JHww+2L5Noh8daCQa3Xtdmh5kt8HoWnIapWTyPtrE50WEkW3goU=
        file_glob: true
        file:
          - ./target/*.obr
          - ./target/*.jar
        skip_cleanup: true
        on:
          tags: true
#          condition: $TRAVIS_TAG =~ ^sequence-
cache:
  directories:
    - $HOME/.m2
