language: java
jdk: openjdk8


before_install:
  - sudo sh -c 'echo "deb https://packages.atlassian.com/debian/atlassian-sdk-deb/ stable contrib" >>/etc/apt/sources.list'
  - wget https://packages.atlassian.com/api/gpg/key/public
  - sudo apt-key add public
  - sudo apt-get update
  - sudo apt-get install atlassian-plugin-sdk
  - atlas-version
install: skip

stages:
  - name: build and release
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch IN (master, cp-29-travis-release-to-github)
jobs:
  include:
    - stage: test
      script: atlas-unit-test
    - stage: build and release
      script:
        - atlas-package
        - ls -l ./target
cache:
  directories:
    - $HOME/.m2
