version: '3'
services:
  confluence:
    image: atlassian/confluence-server
    volumes:
      - .data/confluence:/var/atlassian/application-data/confluence
    ports:
      - "8090:8090"
      - "8091:8091"
