version: '3'
services:
  confluence:
    image: atlassian/confluence-server:7.4.5-jdk11
    volumes:
      - .data/confluence:/var/atlassian/application-data/confluence
    ports:
      - "8090:8090"
      - "8091:8091"
    environment:
      - JVM_MAXIMUM_MEMORY=2048m
