# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build artifacts

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8.0.202'
          java-package: jdk
          architecture: x64
      - run: sudo sh -c 'echo "deb https://packages.atlassian.com/debian/atlassian-sdk-deb/ stable contrib" >>/etc/apt/sources.list'
      - run: wget https://packages.atlassian.com/api/gpg/key/public
      - run: sudo apt-key add public
      - run: sudo apt-get update
      - run: sudo apt-get install atlassian-plugin-sdk
      - run: atlas-version
      - run: atlas-unit-test
      - run: atlas-package
      - run: ls -l ./target
      - name: Upload artifacts  # Find artifacts under actions/jobs
        uses: actions/upload-artifact@v2
        with:
          name: confluence-plugin-addon
          path: ./target/confluence-addon*.jar
